services:
  calculator:
      image: devopsdockeruh/scaling-exercise-calculator
      ports:
        - 3000:3000
      container_name: calculator
  compute:
      image: devopsdockeruh/scaling-exercise-compute
      environment:
        - VIRTUAL_HOST=compute.localtest.me
  load-balancer:
      build: ./load-balancer
      image: load-balancer
      privileged: true
      volumes:
        - /run/user/1000/docker.sock:/tmp/docker.sock:ro
      ports:
        - 80:80
      container_name: load-balancer
