services:
  express-app:
      image: dumbdannot/express-app
      ports:
        - 8080:8080
  watchtower:
      image: containrrr/watchtower
      environment:
        -  WATCHTOWER_POLL_INTERVAL=60 # Poll every 60 seconds
      privileged: true
      volumes:
        - /run/user/1000/docker.sock:/var/run/docker.sock
      container_name: watchtower
